/**
 * Stock management server actions.
 * VAL-EMAR-012: Stock levels, transactions, reorder workflow
 * VAL-EMAR-013: Expiry tracking with batch-level alerts
 * VAL-EMAR-016: Handover report auto-generation
 */
'use server';

import {
  createMedicationStockSchema,
  updateMedicationStockSchema,
  createStockBatchSchema,
  createStockTransactionSchema,
  createReorderRequestSchema,
  updateReorderStatusSchema,
  createHandoverReportSchema,
  type ExpiryAlert,
} from './types';

// ---------------------------------------------------------------------------
// Medication Stock CRUD
// ---------------------------------------------------------------------------

export async function createMedicationStock(
  organisationId: string,
  userId: string,
  data: unknown,
) {
  const parsed = createMedicationStockSchema.parse(data);

  // Validate CD schedule is provided when isControlledDrug is true
  if (parsed.isControlledDrug && !parsed.controlledDrugSchedule) {
    throw new Error('Controlled drug schedule is required for controlled drugs');
  }

  // TODO: Insert into medicationStock table via Drizzle
  // TODO: Create audit log entry
  return { success: true, data: { ...parsed, organisationId } };
}

export async function updateMedicationStock(
  organisationId: string,
  stockId: string,
  userId: string,
  data: unknown,
) {
  const parsed = updateMedicationStockSchema.parse(data);

  // TODO: Update medicationStock record
  // TODO: Create audit log entry
  return { success: true, data: { ...parsed, id: stockId, organisationId } };
}

// ---------------------------------------------------------------------------
// Stock Batch Management (VAL-EMAR-013)
// ---------------------------------------------------------------------------

export async function createStockBatch(
  organisationId: string,
  userId: string,
  data: unknown,
) {
  const parsed = createStockBatchSchema.parse(data);

  // TODO: Insert into stockBatches table
  // TODO: Update medicationStock.currentQuantity
  // TODO: Create stock transaction (receipt)
  // TODO: Create audit log entry
  return { success: true, data: { ...parsed, organisationId } };
}

/**
 * Get batches approaching expiry for an organisation.
 * Returns batches where expiry date is within the configured alert window.
 */
export async function getExpiryAlerts(
  _organisationId: string,
): Promise<ExpiryAlert[]> {
  // TODO: Query stockBatches where:
  //   - organisationId matches
  //   - isExhausted = false
  //   - expiryDate <= now + expiryAlertDays
  // JOIN with medicationStock for medication name
  // Order by expiryDate ASC (most urgent first)
  return [];
}

export async function acknowledgeExpiryAlert(
  _organisationId: string,
  _batchId: string,
  _userId: string,
) {
  // TODO: Update stockBatches set expiryAlertAcknowledged = true
  // TODO: Create audit log entry
  return { success: true };
}

// ---------------------------------------------------------------------------
// Stock Transactions (VAL-EMAR-012)
// ---------------------------------------------------------------------------

export async function recordStockTransaction(
  organisationId: string,
  userId: string,
  data: unknown,
) {
  const parsed = createStockTransactionSchema.parse(data);

  // For controlled drugs, witness is required
  // TODO: Check if medication is CD and enforce witness requirement

  // Calculate new balance
  // TODO: Get current stock level, apply transaction, validate non-negative

  // TODO: Insert into stockTransactions table
  // TODO: Update medicationStock.currentQuantity
  // TODO: If batch specified, update stockBatches.quantity
  // TODO: Check if new quantity <= reorderPoint → auto-generate reorder
  // TODO: Create audit log entry

  return { success: true, data: { ...parsed, organisationId, performedById: userId } };
}

/**
 * Check stock levels and auto-generate reorder requests where needed.
 * Called after each stock transaction or on a schedule.
 */
export async function checkAndGenerateReorders(_organisationId: string, _userId: string) {
  // TODO: Query medicationStock where currentQuantity <= reorderPoint
  // AND no pending/ordered reorderRequest exists for that medication
  // For each: create reorderRequest with isAutoGenerated = true
  return { success: true, reordersGenerated: 0 };
}

// ---------------------------------------------------------------------------
// Reorder Requests (VAL-EMAR-012)
// ---------------------------------------------------------------------------

export async function createReorderRequest(
  organisationId: string,
  userId: string,
  data: unknown,
) {
  const parsed = createReorderRequestSchema.parse(data);

  // TODO: Insert into reorderRequests table
  // TODO: Create audit log entry
  return { success: true, data: { ...parsed, organisationId, requestedById: userId } };
}

export async function updateReorderStatus(
  organisationId: string,
  reorderId: string,
  userId: string,
  data: unknown,
) {
  const parsed = updateReorderStatusSchema.parse(data);

  // If status is 'received' or 'partially_received':
  //   TODO: Create stock transaction (receipt) for quantityReceived
  //   TODO: Update medicationStock.currentQuantity

  // If status is 'cancelled':
  //   TODO: Validate cancellation reason is provided

  // TODO: Update reorderRequests record
  // TODO: Create audit log entry
  return { success: true, data: { ...parsed, id: reorderId, organisationId } };
}

export async function notifyPharmacy(
  _organisationId: string,
  _reorderId: string,
  _userId: string,
) {
  // TODO: Mark pharmacyNotified = true, pharmacyNotifiedAt = now
  // TODO: Send notification (email/integration)
  // TODO: Create audit log entry
  return { success: true };
}

// ---------------------------------------------------------------------------
// Handover Reports (VAL-EMAR-016)
// ---------------------------------------------------------------------------

/**
 * Auto-generate a handover report for a shift.
 * Compiles medication events from the shift period.
 */
export async function generateHandoverReport(
  organisationId: string,
  userId: string,
  data: unknown,
) {
  const parsed = createHandoverReportSchema.parse(data);

  // TODO: Query administration records within shift period
  // TODO: Compile refusals, PRN usage, errors
  // TODO: Calculate CD balances
  // TODO: Insert into handoverReports table
  // TODO: Create audit log entry

  return { success: true, data: { ...parsed, organisationId, generatedById: userId } };
}

export async function signHandoverReport(
  _organisationId: string,
  _reportId: string,
  _userId: string,
  _role: 'outgoing' | 'incoming',
) {
  // TODO: Update the appropriate signature field
  // TODO: If both signed, set isCompleted = true
  // TODO: Create audit log entry
  return { success: true };
}
